#!/usr/bin/env bash

# Function to display information about a specific subdomain
display_subdomain_info() {
    domain=$1
    subdomain=$2
    record_type=$(dig $subdomain.$domain | awk '/^;; ANSWER SECTION:/ {getline; print $4}')
    destination=$(dig $subdomain.$domain | awk '/^;; ANSWER SECTION:/{getline; print $NF}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Function to display information about default subdomains
display_default_subdomains_info() {
    domain=$1
    display_subdomain_info $domain www
    display_subdomain_info $domain lb-01
    display_subdomain_info $domain web-01
    display_subdomain_info $domain web-02
}

# Main function
main() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        display_default_subdomains_info $domain
    else
        display_subdomain_info $domain $subdomain
    fi
}

# Check if domain and subdomain parameters are provided
if [ "$#" -eq 0 ]; then
    echo "Error: Domain name is missing"
    exit 1
elif [ "$#" -gt 2 ]; then
    echo "Error: Too many arguments"
    exit 1
fi

# Call main function
main "$1" "$2"

