#!/usr/bin/env bash
# write a script to install nginx on server web-01
#+ listening on port 80

# installation
apt-get update
apt-get install -y nginx

# file creation
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

# configuration
sudo bash -c 'echo "server {
    listen    80 default_server;
    listen    [::]:80 default_server;
    root      /etc/nginx/html;
    index     index.html index.htm;
}" > /etc/nginx/sites-available/default'

# restart nginx
service nginx restart