#!/usr/bin/env bash
# write a script to install nginx on server web-01
#+ listening on port 80

# installation
apt-get update
apt-get install -y nginx

# file creation
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

# start nginx
service nginx start

# configuration
sudo bash -c 'echo "server {
    listen 80;
    server_name _;

    location / {
        root /etc/nginx/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default'

# restart nginx
service nginx restart