#!/usr/bin/env bash
# configuring nginx server so /redirect_me is redirecting
#+ to another page using 301 (permanent redirection)

./1-install_nginx_web_server

read -r -d '' redirect_rule <<'EOF'
location /redirect_me/ {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOF

if [ -f /etc/nginx/sites-available/default ]; then
    cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
    awk -v r="$redirect_rule" '/server_name _;/ {print; print r; next} 1' /etc/nginx/sites-available/default > /etc/nginx/sites-available/default.tmp && mv /etc/nginx/sites-available/default.tmp /etc/nginx/sites-available/default
else
    echo "Default server block configuration file not found"
    exit 1
fi

service nginx reload