#!/usr/bin/env bash
# configuring nginx server so /redirect_me is redirecting
#+ to another page using 301 (permanent redirection)

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
makedir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

NGINX_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
        if (\$request_uri ~* ^/redirect_me) {
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}"

bash -c "echo -e '$NGINX_CONFIG' > /etc/nginx/sites-enabled/default"

service nginx restart
