#!/usr/bin/env bash
# configuring nginx server so /redirect_me is redirecting
#+ to another page using 301 (permanent redirection)

nginx_config_file="/etc/nginx/sites-available/default"

redirection_config="location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

cp "$nginx_config_file" "$nginx_config_file.bak"

sed -i "/# REDIRECTION_CONFIG/r /dev/stdin" "$nginx_config_file" <<< "$redirection_config"

nginx -t

service nginx restart