#!/usr/bin/env bash
# installs and configures server to include custom header: 'X-Served-By'
#+ value of header is hostname server it is running on

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

custom_header="add_header X-Served-By \"$HOSTNAME\";"

if ! grep -q "$custom_header" /etc/nginx/nginx.conf
then
    sudo sed -i "/http {/a \\\t$custom_header" /etc/nginx/nginx.conf
fi

sudo service nginx restart