#!/usr/bin/env bash
# install and configure load balancer to distribute http requests
#+ between web-01 and web-02 servers

# installation
apt-get -y update
apt-get -y install haproxy

# configuration
DOMAIN_NAME='onepimeht.tech'
 
echo "backend $DOMAIN_NAME-servers
    balance roundrobin
    mode http
    server 7136-web-01 100.26.213.55:80 check
    server 7136-web-02 54.236.45.113:80 check

frontend $DOMAIN_NAME-in
    bind *:80
    mode http
    default_backend $DOMAIN_NAME-servers
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start