#!/usr/bin/env bash
# Script that pings an IP address passed as an argument.
# Accepts a string as an argument
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no arg
# Ping the IP 5 times

if [ "$#" -eq 0 ]
then
	echo "Usage: $0 {IP_ADDRESS}"
else
	ip_address="$1"

	ping -c 5 "$ip_address"
fi
