#!/usr/bin/env bash
# setup nginx in container to listen and make sure it is installed properly
rm -rf /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart