#!/usr/bin/env bash
# creates file containing file pid, has infinite loop

echo $$ > /var/run/myscript.pid

clean()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

trap 'clean' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true
do
	echo "To infinity and beyond"
done
