#!/usr/bin/env bash
# creates file containing file pid, has infinite loop

echo $$ > /var/run/myscript.pid

trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT SIGTERM

while true
do
	echo "To infinity and beyond"
done
