#!/usr/bin/env bash
# loop through 1 to 10 an print special text at 4th and 8th iter.

x=0
while [ $x -lt 10 ]
do
	if [ $x -eq 3 ]
	then
		echo "bad luck"
	elif [ $x -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
