#!/usr/bin/env bash
# configures the container to be running as nginx user
#+ listening on all active IPs on port 8080

# Modify the nginx configuration to run as the nginx user and listen on port 8080
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Modify chmod of nginx.conf
chmod 644 /etc/nginx/nginx.conf

# pkill apache2
pkill apache2

# Restart Nginx to apply the changes
sudo -u nginx service nginx restart

