#!/usr/bin/env bash
# configures the container to be running as nginx user listening on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart

